### ISSUE TITLE
godot 4.0 new tilemap

### ISSUE THREAD

**Issue by Euraxluo** [DennisSmuda/godot-chunking-system#3]
Do you have any plans to update it

**Comment by DennisSmuda** [comment]
@Euraxluo yes thanks for the reminder!

**Comment by DennisSmuda** [comment]
@Euraxluo I have ported this to Godot4 - see [this PR](https://github.com/DennisSmuda/godot-chunking-system/pull/4)

You metioned `tilemap` in your title? So far I'm just using individual tiles as scenes though. I will do that as a seperate feature 👍
