### ISSUE TITLE
Save and load data

### ISSUE THREAD

**Issue by ciso507** [DennisSmuda/godot-chunking-system#5]
Couls you make a save and load data system so when the player access the scene and close it it will display the same tiles that he already revealed on the first run? I was trying this myself but its difficult 😔

**Comment by DennisSmuda** [comment]
Hey @ciso507 I think it's out of scope for this repo - I might make a seperate thing for this at some point.

I haven't looked at save/loading in godot4 yet but [it seems similar to godot3](https://kidscancode.org/godot_recipes/4.x/basics/file_io/)

For what you want to achieve, you'd need a couple of things actually:

1. The "noise" data (or just use a fixed seed at first)
2. "Revealed Chunks" -> add a `has_discovered=true` property to the chunk
3. A save/load system -> buttons in a pause menu or something

When you start the game, you can `load` your previously discovered chunks. 
You would need to test out "when" to save the game - probably in a pause-state, so you won't impact game-performance

Hope this helps :)

**Comment by ciso507** [comment]
thanks a lot @DennisSmuda I was able to save the seed and everything its been replicated now what im missing here is how would i update the tile that i have modified by right_click .. or when an area enters and then save it. Im even thinking on just instanciate every tilemap in a global.tilemap... and then work like that it still kinda works it would be also simple for me to add the save data for the tiles that has been updated.

**Comment by DennisSmuda** [comment]
@ciso507 As I understand it, you need to use "Resources"  (`.tres`) in your actual "tiles". It can't be "just a plain sprite" but it needs to have properties like `has_discovered` and/or `is_visible` that you can then save and load.

I'm looking into making this a proper plugin - [see issue](https://github.com/DennisSmuda/godot-chunking-system/issues/6) - I will definitely have to consider people wanting to save/load their chunks ;)
